#!/usr/bin/env node
// -*- mode: js -*-
// Copyright 2011 Joyent, Inc.  All rights reserved.

var path = require('path');

var ldap = require('ldapjs');
var log4js = require('log4js');
var nopt = require('nopt');



///--- Globals

nopt.typeDefs.LdapUrl = {
  type: ldap.url,
  validate: function(data, k, val) {
    try {
      if (!ldap.parseURL(val + ''))
        return false;

      data[k] = val;
    } catch (e) {
      return false;
    }
  }
};

var opts = {
  'base': String,
  'binddn': String,
  'debug': Boolean,
  'help': Boolean,
  'filter': String,
  'passwd': String,
  'scope': String,
  'url': ldap.url
};

var shortOpts = {
  'D': ['--binddn'],
  'b': ['--base'],
  'd': ['--debug'],
  'h': ['--help'],
  's': ['--scope'],
  'u': ['--url'],
  'w': ['--passwd']
};



///--- Internal Functions

function usage(code, message) {
  var _opts = '';
  Object.keys(shortOpts).forEach(function(k) {
    var longOpt = shortOpts[k][0].replace('--', '');
    var type = opts[longOpt].name || 'string';
    if (type && type === 'boolean') type = '';
    type = type.toLowerCase();

    _opts += ' [--' + longOpt + ' ' + type + ']';
  });
  var msg = (message ? message + '\n' : '') +
    'usage: ' + path.basename(process.argv[1]) + _opts;

  process.stderr.write(msg + '\n');
  process.exit(code);
}


function ifError(err) {
  if (!err) return;

  process.stderr.write(err.message + '\n');
  process.exit(1);
}


///--- Mainline

log4js.setGlobalLogLevel('INFO');

var parsed = nopt(opts, shortOpts, process.argv, 2);

if (parsed.help)
  usage(0);

if (!parsed.passwd)
  usage(1, '--passwd required');

if (!parsed.binddn)
  parsed.binddn = 'cn=root';

if (!parsed.base)
  parsed.base = 'o=smartdc';

if (!parsed.scope)
  parsed.scope = 'sub';

if (!parsed.filter)
  parsed.filter = '(objectclass=*)';

if (!parsed.url)
  parsed.url = 'ldap://localhost';

if (parsed.debug)
  log4js.setGlobalLogLevel('TRACE');

var client = ldap.createClient({
  url: parsed.url,
  log4js: log4js
});

client.bind(parsed.binddn, parsed.passwd, function(err) {
  ifError(err);

  var req = {
    scope: parsed.scope,
    filter: parsed.filter
  };

  client.search(parsed.base, req, function(err, res) {
    ifError(err);

    var entries = [];
    res.on('searchEntry', function(entry) {
      entries.push(entry.object);
    });
    res.on('error', function(err) {
      ifError(err);
    });
    res.on('end', function(result) {
      client.unbind(function(err) {
        ifError(err);

        process.stdout.write(JSON.stringify(entries, null, 2) + '\n');
      });
    });
  });
});
